name: 🦕 Deploy Docusaurus to GitHub Pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - env:
          DOCUACTIONS_TOKEN: ${{ secrets.DOCUACTIONS_TOKEN }}
          DOCUACTIONS_DEPLOYMENT: ${{ secrets.DOCUACTIONS_DEPLOYMENT }}
      - uses: actions/checkout@v2
      - uses: docuactions/github-pages@main
        
