name: 🦕 Deploy Docusaurus to GitHub Pages
on: [push]
env:
    DOCUACTIONS_TOKEN: ${{ secrets.DOCUACTIONS_TOKEN }}
    DOCUACTIONS_DEPLOYMENT: ${{ secrets.DOCUACTIONS_DEPLOYMENT }}

        
jobs:
  deploy:
    
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - uses: docuactions/github-pages@main
